### ISSUE TITLE
Build on Ubuntu 20.04/22.04/23.04/23.10

### ISSUE THREAD

**Issue by lucasw** [lucasw/gephex#40]
Get rid of qt4

make new `main` branch -> https://github.com/lucasw/gephex/tree/ubuntu_20_04 for now until it builds

do a search and replace on cmake minimum version

```
cmake ../../src/gephex/ -DCMAKE_CXX_STANDARD=11 -DCMAKE_INSTALL_PREFIX=$DEST
```

Update python 2 code

-> the cmake ought to include this directory

```
cmake ../../src/gephex/ -DCMAKE_CXX_STANDARD=11 -DCMAKE_INSTALL_PREFIX=$DEST -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=/usr/include/x86_64-linux-gnu/qt5
```

**Comment by lucasw** [comment]
```
/home/lucasw/other/src/gephex/qtgui/src/gui/vjmainwindow.cpp: In constructor ‘gui::VJMainWindow::VJMainWindow(QWidget*, const utils::ConfigManager&, const std::string&, const std::string&)’:
/home/lucasw/other/src/gephex/qtgui/src/gui/vjmainwindow.cpp:132:65: error: no matching function for call to ‘gui::PicSwitch::PicSwitch(QStatusBar*, const char* [71], const char* [85])’
  132 |   switcher = new PicSwitch(statusBar(), roter_mann, gruener_mann);
      |                                                                 ^
In file included from /home/lucasw/other/src/gephex/qtgui/src/gui/vjmainwindow.cpp:48:
/home/lucasw/other/src/gephex/qtgui/src/gui/picswitch.h:36:3: note: candidate: ‘gui::PicSwitch::PicSwitch(QWidget*, const QPixmap&, const QPixmap&)’
   36 |   PicSwitch(QWidget *parent, const QPixmap &pm1, const QPixmap &pm2);
      |   ^~~~~~~~~
/home/lucasw/other/src/gephex/qtgui/src/gui/picswitch.h:36:45: note:   no known conversion for argument 2 from ‘const char* [71]’ to ‘const QPixmap&’
   36 |   PicSwitch(QWidget *parent, const QPixmap &pm1, const QPixmap &pm2);
      |                              ~~~~~~~~~~~~~~~^~~
```

->   
```
switcher = new PicSwitch(statusBar(), QPixmap(roter_mann), QPixmap(gruener_mann));
```

**Comment by lucasw** [comment]
It's building now, but not finding modules- no ran again and it does show modules in the stdout, but not in the gui.

Also install didn't copy in example graphs
```
cd ~/other/src/gephex
cp -rfupv examples/graphs/* ~/.gephex/0.4/graphs/
```

Maybe this is why the gui is coming up mostly unpopulated:
```
protocol.cpp, dataReceived of listener throwed: could not scan tag
```
(this is on client side)

nic.py is generating code related to this (`createNetIfaceSendImpl`, `Buffer`), probably messed something up in there

Did I ever tar up an entire build directory from a 16.04 system?  Ought to compare _auto.c files- could try the source distribution here https://gephex.org/download.php but those aren't going to have the intermediate files.

Try compiling base/src/utils/testmain.cpp and related code (which wasn't updated even for 16.04)

---

Is this networking test supposed to get out of sync?

```
./base/src/net/nettest 
...
 Test: Protocol
 
.................................protocol.cpp: out of sync!
pl = 29, dl = 6
Trying to resync protocol...
Skipping 6 bytes
pl = 21, dl = 5
 OK
```

Try setting ENGINE_VERBOSITY to > 0, 3 for starting


---

od a debug build

```
cmake ../../src/gephex/ -DCMAKE_CXX_STANDARD=11 -DCMAKE_INSTALL_PREFIX=$DEST -DCMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES=/usr/include/x86_64-linux-gnu/qt5 -DCMAKE_BUILD_TYPE=Debug
```

**Comment by lucasw** [comment]
Debug the client/gui receptions of packets:

```
break xmlutils.cpp:134
run
...
134	void checktag(std::istream &s, const std::string &giventag) {
(gdb) bt
#0  utils::checktag(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (s=..., giventag="<str>")
    at /home/lucasw/other/src/gephex/base/src/utils/xmlutils.cpp:134
#1  0x00005555556e33a8 in utils::operator>>(std::basic_istream<char, std::char_traits<char> >&, utils::String&) (s=..., str=...) at /home/lucasw/other/src/gephex/base/src/utils/string_.cpp:55
#2  0x00005555556cca69 in ModuleClassInfoSenderNet::dataReceived(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, utils::Buffer const&)
    (this=0x5555559945a0, command="0000", buf=...) at /home/lucasw/other/build/gephex_debug/base/src/netinterfaces/netinterfaces/moduleclassinfosendernet.cpp:35
#3  0x00005555556c8ce9 in net::Tagger<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, net::StringTagUtil>::dataReceived(utils::Buffer const&)
    (this=0x5555559cf110, taggedData=...) at /home/lucasw/other/src/gephex/base/src/net/tagger.cpp:64
#4  0x00005555556c894a in net::TagDispatcher<unsigned int>::dataReceived(unsigned int const&, utils::Buffer const&) (this=0x55555598d510, tag=@0x7fffffffd10c: 6667, b=...)
    at /home/lucasw/other/src/gephex/base/src/net/tagdispatcher.cpp:51
#5  0x00005555556c8b0b in net::Tagger<unsigned int, net::UInt32TagUtil>::dataReceived(utils::Buffer const&) (this=0x5555559946f0, taggedData=...)
    at /home/lucasw/other/src/gephex/base/src/net/tagger.cpp:64
#6  0x00005555556eb2d9 in net::Protocol::dataReceived(utils::Buffer const&) (this=0x555555980610, buf=...) at /home/lucasw/other/src/gephex/base/src/net/protocol.cpp:278
#7  0x00005555556ecacf in net::SocketAdaptor::run() (this=0x5555559adec0) at /home/lucasw/other/src/gephex/base/src/net/socketadaptor.cpp:48
#8  0x00005555556c4b9d in gui::EngineWrapper::checkData() (this=0x5555558e5970) at /home/lucasw/other/src/gephex/qtgui/src/guimodel/enginewrapper.cpp:182
#9  0x0000555555685c3d in gui::VJMainWindow::pollNetwork() (this=0x7fffffffd930) at /home/lucasw/other/src/gephex/qtgui/src/gui/vjmainwindow.cpp:232
#10 0x0000555555659518 in gui::VJMainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x7fffffffd930, _c=QMetaObject::InvokeMetaMethod, _id=12, _a=0x7fffffffd3f0)
    at /home/lucasw/other/build/gephex_debug/qtgui/src/gui/moc_vjmainwindow.cpp:156
#11 0x00007ffff6cf39dc in doActivate<false>(QObject*, int, void**) (sender=0x55555596a5b0, signal_index=3, argv=0x7fffffffd3f0) at kernel/qobject.cpp:3935
#12 0x00007ffff6ceca47 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**)
    (sender=<optimized out>, m=m@entry=0x7ffff6f5a2e0 <QTimer::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fffffffd3f0) at kernel/qobject.cpp:3983
#13 0x00007ffff6cf798e in QTimer::timeout(QTimer::QPrivateSignal) (this=<optimized out>, _t1=...) at .moc/moc_qtimer.cpp:205
#14 0x00007ffff6ce7bf5 in QObject::event(QEvent*) (this=0x55555596a5b0, e=0x7fffffffd540) at kernel/qobject.cpp:1369
#15 0x00007ffff796bf92 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x55555596a5b0, e=0x7fffffffd540) at kernel/qapplication.cpp:3640
#16 0x00007ffff6cbae38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x55555596a5b0, event=0x7fffffffd540) at kernel/qcoreapplication.cpp:1064
#17 0x00007ffff6cbb012 in QCoreApplication::sendEvent(QObject*, QEvent*) (receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1462
```

It seems like there is nothing left in the buffer at this line, bs is empty resulting in no moduleClassName

```
bs  >> moduleClassName >> buf;
```
moduleclassinfosendernet.cpp - this is generated from `.if` files



try building in 20.04 in Docker

**Comment by lucasw** [comment]
Running inside docker (having built with python2) almost works with https://github.com/lucasw/gephex/tree/ubuntu_20_04, can see gui and effects but trying to start the output results in this:

```

@log@ [mod_frboutmodule]:> Using x11 output driver
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  1 (X_ShmAttach)
  Serial number of failed request:  10
  Current serial number in output stream:  11
protocol.cpp: send threw Socket not connected at FDSocket::send!
silent mode turned on
```

-> `--ipc host` fixes this, now can see the output window

Just need some more docker volumes exposed to be able to save graphs and not have to re-run make install

---

That branch has all the same qt changes, only has python changes, so the python changes must be responsible for the issues- can inspect the generated output and look for discrepancies

[gephex_docker_build.zip](https://github.com/lucasw/gephex/files/13763026/gephex_docker_build.zip)

---

Tried the combinations of talking to the docker gephex server from the outside and client on the inside, and all got the `protocol.cpp, dataReceived of listener throwed: could not scan tag` error - there's some communication breakdown there, but at least can instrument the working server-client in the docker and see how to fix it.

```
gephex
...
numarithmodule.so
bwmodule.so
@log@ [mod_frbinmodule]:> setting up cache: 128 mb
load modules from dir: /root/.frei0r-1/lib/ .so
load modules from dir: /usr/local/lib/frei0r-1/ .so
load modules from dir: /usr/lib/frei0r-1/ .so
@error@ [Model]:> no graph with that name 'default' (GraphFileSystem::loadGraph)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
  media_path	= /other/install/share/gephex
  ipc_type	= inet
  ipc_inet_hostname	= localhost
  ipc_namedpipe_servername	= .
  ipc_unix_node_prefix	= /tmp/gephex_socket_
  ipc_port	= 6666
  engine_binary	= /other/install/bin/gephex-engine
libGL error: MESA-LOADER: failed to retrieve device information
adding sink: 1 mod_frboutmodule, num_outputs: 0, is deterministic: 0
adding sink: 2 mod_isingnoizemodule, num_outputs: 1, is deterministic: 0
@log@ [mod_frboutmodule]:> Using x11 output driver
 x11output: using Xv extension
 x11output: using XShm extension
```

The last few lines are adding some modules

There are some differences in `INFO` sections of modules, are those enough to foul up communication- do they need to be exact?

---

Can run the docker built binaries on the outside too (thanks to static linking), so there's another route to testing- get communication problems only when trying to run the outside-built gephex-gui-real to talk to the docker built gephex-engine-real

---

Using the exact same code can switch back and forth between python2 and python3 inside the 20.04 docker (apt install python-is-python2 or python-is-python3), and the python3 generated code doesn't work, python2 is fine- so it's not necessarily that my updates to python3 compatible code were completely wrong, it's that python implements some of the functions differently?  (and it's not the fault of different C++ versions or qt libraries)  Look at the differences in generated files by creating a one-off local git, check in all the nic.py and pluc.py generated files.

```
find . | grep \\.h | xargs git add
find . | grep cpp$ | xargs git add
find . | grep _auto.c$ | xargs git add
```

Now can see the issue plainly

```
diff --git a/base/src/netinterfaces/netinterfaces/controlvaluereceivernet.cpp b/base/src/netinterfaces/netinterfaces/controlvaluereceivernet.cpp
index 709a9b8..ef787d2 100644
--- a/base/src/netinterfaces/netinterfaces/controlvaluereceivernet.cpp
+++ b/base/src/netinterfaces/netinterfaces/controlvaluereceivernet.cpp
@@ -14,10 +14,7 @@ ControlValueReceiverNet::~ControlValueReceiverNet()
 
 void ControlValueReceiverNet::controlValueChanged( int nodeID, int intputIndex, const utils::Buffer& newValue )
 {
-       utils::Buffer temp_buf_(48);
-       utils::OBufferStream bs(temp_buf_);
-       bs << nodeID << ' '  << intputIndex << ' '  << newValue;
-       bs.flush();
+       utils::Buffer temp_buf_((unsigned char*) "",1);
        m_tagger->setTag( "0000" );
        m_tagger->send( temp_buf_ );
```

[gephex_generated_python2vs3.zip](https://github.com/lucasw/gephex/files/13766621/gephex_generated_python2vs3.zip)

**Comment by lucasw** [comment]
Fixed issue https://github.com/lucasw/gephex/commit/c0f227118ea87cee965d2a6f1ce3c8dd8276b68c - needed to convert map to list for python3 (python 2 returned list)

Next clean up commits and put this into default branch (and make default branch `main`), do github action, fix up some of the warnings, but this is good enough for now

**Comment by lucasw** [comment]
graphs aren't saving currently, see if that was working in docker build


maybe related:
```
@error@ [Model]:> no graph with that name 'default' (GraphFileSystem::loadGraph)
```

It looks like it saved one in the current directory I launched gephex from, but not seeing additional files 

No other are saved in .gephex/0.4, just without a / e.g. lnoise -> graphslnoise instead of graphs/lnoise

Try a trailing slash in conf:

```
graph_path           = [/home/lucasw/.gephex/0.4/graphs/
```

that works, should add a trailing slash or make sure the template gephex.conf has it
